version: "3.8"

services:
  frontend:
    image: abhisheksingh1909/fstore-frontend
    ports:
      - "3000:3000"

  backend:
    image: abhisheksingh1909/fstore-backend
    ports:
      - "8080:8080"
